spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecom-product
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
server:
  port: 8070

application:
  config:
    customer-url: http://localhost:8222/api/v1/customer
    payment-url: http://localhost:8222/api/v1/payment
    product-url: http://localhost:8222/api/v1/product